export const SET_USERS = 'SET_USERS';
export const SET_SEARCHING_CRITERIA = 'SET_SEARCHING_CRITERIA';
export const SET_SORTING_CRITERIA = 'SET_SORTING_CRITERIA';
export const SET_ASCENDING_ORDER = 'SET_ASCENDING_ORDER';
